name: Remark

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  remark:
    runs-on: ubuntu-latest

    steps:
    # Setup
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Setup Node.js
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '12.x'

    - name: Install remark
      run: npm install remark-cli remark-lint remark-lint-maximum-line-length remark-preset-lint-recommended remark-gfm

    # Run
    - name: Check *.md files
      run: git ls-files '*.md' | xargs npx remark -q -f -u lint > /dev/null

  # ALL THE PREVIOUS JOBS NEED TO BE ADDED TO THE `needs` SECTION OF THIS JOB!

  end-success:
    name: bors remark test finished success
    if: github.event.pusher.name == 'bors' && success()
    runs-on: ubuntu-latest
    needs: [remark]

    steps:
      - name: Mark the job as successful
        run: exit 0

  end-failure:
    name: bors remark test finished failed
    if: github.event.pusher.name == 'bors' && (failure() || cancelled())
    runs-on: ubuntu-latest
    needs: [remark]

    steps:
      - name: Mark the job as a failure
        run: exit 1
